# Generated by Django 6.0.3 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidplain', '0003_conversation_chatmessage_conversationfeedback'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='msg_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'bot_type', '-updated_at'], name='conv_user_bot_updated_idx'),
        ),
    ]
